### ISSUE TITLE
希望能写一篇搭建自己开发UI框架思路和总结

### ISSUE THREAD

**Issue by Niofh** [xuqiang521/my-element-ui#1]
因为不知道怎么把vue组件封装成组件库，在vue-cli需要修改什么？还有注意什么，发布的时候怎么发布？

**Comment by xuqiang521** [comment]
你可以关注我 vui 的开发动态（star 或者 watch 都可以），后期组件差不多完工会写一篇相关的文章做总结的，目前 vui 新地址为 https://github.com/Brickies/vui

**Comment by dkvirus** [comment]
+1，新工程也看了下，并没有看到介绍搭建框架的文章。
